version: '3'
services:

  database:
    image: mysql:5.7
    container_name: database
#    restart: always
    ports:
     - "3309:3306"
    volumes:
     - ./mysql:/var/lib/mysql
     - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
     - ./files:/var/lib/mysql-files
    env_file: .env  
       
  admin:
    image: phpmyadmin:latest
    container_name: admin
#    restart: always
    ports:
     - "8051:80"
    env_file: .env

  public:
    build: ./
    container_name: public
#    restart: always
    ports:
     - "8050:80"
    env_file: .env
    volumes:
     - ./public:/var/www/html