version: '3'
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
     - "${MYSQL_PORTS}:${MYSQL_PORTS}"
    volumes:
     - ./mysql:/var/lib/mysql:rw
     - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:rw
     - ./files:/var/lib/mysql-files:rw
     - ./web_scraping.sql:/docker-entrypoint-initdb.d/web_scraping.sql:rw
    env_file: .env
    networks:
      - network1

  php:
    build: ./
    container_name: php
    ports:
     - "${PHP_PORTS}:${PHP_PORTS}"
    env_file: .env
    volumes:
     - ./public:/var/www/html:rw
    networks:
      - network1

networks:
  network1:
    name: ${DOCKER_NETWORK}
    external: true