version: '3'
services:

  database:
    image: mysql:5.7
    container_name: database
#    restart: always
    ports:
     - "3309:3306"
    volumes:
     - ./mysql:/var/lib/mysql
     - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
     - ./files:/var/lib/mysql-files
     - ./web_scraping.sql:/docker-entrypoint-initdb.d/web_scraping.sql
    env_file: .env
    networks:
      - network1

  public:
    build: ./
    container_name: public
#    restart: always
    ports:
     - "8085:8085"
    env_file: .env
    volumes:
     - ./public:/var/www/html
    networks:
      - network1

networks:
  network1:
    name: nginx_docker_web
    external: true